### ISSUE TITLE
fly.io error on start hallpass exited, status: signal: 15 (SIGTERM)

### ISSUE THREAD

**Issue by KingPin** [tailscale-dev/tclip#24] opened 2023-08-21 17:49 UTC
setup a fly.io account, following the commands from readme to deploy tclip, but it keeps exiting/crashing and then runs out of restarts after a while. tailscale admin panel shows the machine as having been added successfully. 

fly.toml : 
```
app = "tclip"
primary_region = "ewr"

[build]
image = "ghcr.io/tailscale-dev/tclip:latest"

[deploy]
strategy = "immediate"

[env]
DATA_DIR = "/data"
USE_FUNNEL = "true"

[mounts]
source = "tclip_data"
destination = "/data"
```

log from fly.io:
```
2023-08-21T17:43:54.494 app[3908032c91d087] ewr [info] [ 0.040568] PCI: Fatal: No config space access function found
2023-08-21T17:43:54.719 app[3908032c91d087] ewr [info] INFO Starting init (commit: b437b5b)...
2023-08-21T17:43:54.730 app[3908032c91d087] ewr [info] INFO Mounting /dev/vdb at /data w/ uid: 0, gid: 0 and chmod 0755
2023-08-21T17:43:54.733 app[3908032c91d087] ewr [info] INFO Resized /data to 3217031168 bytes
2023-08-21T17:43:54.735 app[3908032c91d087] ewr [info] INFO Preparing to run: `/nix/store/wmrf0b1i95cxli7iq44qjl62-tclip-web-0.1.0-20230817/bin/web` as root
2023-08-21T17:43:54.742 app[3908032c91d087] ewr [info] INFO [fly api proxy] listening at /.fly/api
2023-08-21T17:43:54.745 app[3908032c91d087] ewr [info] 2023/08/21 17:43:54 listening on [fdaa:2:d361:a7b:1:1:1:2]:22 (DNS: [fdaa::3]:53)
2023-08-21T17:43:56.904 app[3908032c91d087] ewr [info] 2023/08/21 17:43:56
2023-08-21T17:43:56.904 app[3908032c91d087] ewr [info] 2023/08/21 17:43:56 HTTPS is not enabled in the admin panel
2023-08-21T17:43:57.746 app[3908032c91d087] ewr [info] INFO Main child exited normally with code: 1
2023-08-21T17:43:57.746 app[3908032c91d087] ewr [info] INFO Starting clean up.
2023-08-21T17:43:57.747 app[3908032c91d087] ewr [info] INFO Umounting /dev/vdb from /data
2023-08-21T17:43:57.749 app[3908032c91d087] ewr [info] WARN hallpass exited, pid: 264, status: signal: 15 (SIGTERM)
2023-08-21T17:43:57.753 app[3908032c91d087] ewr [info] 2023/08/21 17:43:57 listening on [fdaa:2:d361:a7b:1:1:1:2]:22 (DNS: [fdaa::3]:53)
2023-08-21T17:43:58.749 app[3908032c91d087] ewr [info] [ 4.291233] reboot: Restarting system
2023-08-21T17:43:58.855 runner[3908032c91d087] ewr [info] machine did not have a restart policy, defaulting to restart
```

**Comment by Erisa** [comment] 2024-07-15 21:45
Hi @KingPin sorry for the radio silence here - are you able to try this again and see if you still have the same error? The `fly.toml` visually looks good and I'm not able to reproduce the same issue.

**Comment by Erisa** [comment] 2024-09-06 03:00
Hi again, I'm going to close this issue for now but if you do run into this issue again please respond here and it can be reopened. Thanks!

**Closed by Erisa** 2024-09-06 03:00 UTC
Labels: bug, fly.io, waiting for response
